---
output: html_document
---


### The Dataset

Starting in 2017-18, the NBA began publishing data that tracked the time each player spent guarding opposing players during a game, as well as the counting stats accumulated by the player and his team during that time. As a result, player performance in any given matchup is available across multiple seasons, including the playoffs. This app provides querying functionality for this data and summarizes the performance of each player selected.

Important to note, the algorithm used to track this matchup level data was updated in advance of the 2019-20 season. Most notable of these updates was field goal attempts being attributed to the defender who is matched up to the offensive player at the time of the shot, rather than the player that defended the shot taker for the majority of the possession. Given the issues this presents for the 2017-18 and 2018-19 data, those seasons are excluded from the default settings on the dashboard. However, they are available to include if the user chooses.

More information on NBA matchup tracking as well as the updates made prior to the 2019-20 season can be found [here](https://www.nba.com/stats/articles/nba-com-stats-unveils-improved-matchup-data-for-2019-20-season/). 


### Metrics

Metrics used to evaluate player performance are as follows:

##### Scoring
 - Points per 100 possessions
 - Points per shot
 - Effective FG % (more info [here](https://www.basketball-reference.com/about/glossary.html))
 
##### Playmaking
 - Points scored & asisted on per 100 (assumes each ast results in 2.4 pts based on league avg 3pt attempt frequency)
 - Assists per 100
 - Turnovers per 100
 - Assist/Turnover ratio
 
##### Foul Drawing
 - Shooting fouls per shot
 - FT attempts per 100
 
##### Other
 - Blocks per 100

### Plot

Displays offensive player's performance against each listed defender for the selected metric. Offensive player's metric average across all matchups in the seasons selected is also plotted as a vertical perforated line for reference.

Additional contextual features include the sample size of possessions for each matchup, as well as the 3pt% shot by the offensive player. Given the high degree of "make-or-miss" inherent in NBA 3pt shooting and the impact that 3pt% variance has on scoring results (particularly with low samples), offensive player 3pt% for each matchup is included as a contextual element to consider whether extreme 3pt% variance may have an impact on certain results (point colored grey if no 3pt attempts).


### Table

 - **Possessions**: Sum of possessions (partial and full) in which defender was guarding offensive player for selected time period.
 - **% of Time Defended**: The percent of time both players were on the floor and the defender was guarding the offensive player
 - **Shots per 100**: Included to represent how aggressive the offensive player was from a scoring perspective in a given matchup
 - **3pt %**: Included to consider whether extreme 3pt% variance may be impacting results (if blank, player hasn't attempted a 3pt shot in a given matchup)
 - **Percent Rank**: How defender compares to all other defenders guarding the offensive player for the selected metric over the selected period


### Odds & Ends

Data used to generate this app was obtained from [PBP Stats Tracking](https://tracking.pbpstats.com/) by way of [NBA.com](https://www.nba.com/stats/)

App created by Alex Merg. Data and code available on [GitHub](https://github.com/a-merg/nba_matchup_finder).

<br></br>